
class Planets {
  final String id;
  final String name;
  final String image;
  final String desc;
  final List<String> images;

  Planets(this.id,this.name,this.image,this.desc,this.images);
}

List<Planets> planets = [
  Planets('1','Mercury','assets/images/mercury.png','Mercury is the smallest and innermost planet in the Solar System. Its orbit around the Sun takes 87.97 days, the shortest of all the planets in the Solar System. It is named after the Greek god Hermes (Ερμής), translated into Latin Mercurius Mercury, god of commerce, messenger of the gods, mediator between gods and mortals.',['https://cdn.mos.cms.futurecdn.net/GA4grWEsUYUqH58cDbRBw8.jpg','https://i.pinimg.com/originals/12/9b/c2/129bc2f7a2f846fd071aaba2675d5c13.jpg','https://s.yimg.com/ny/api/res/1.2/fgvKkS2Gja9T.6fcdM8Z4A--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9ODAw/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2019-08/80435c50-b4d6-11e9-99df-b1cd6cb27c78']),
  Planets('2','Venus','assets/images/venus.png','Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the second-brightest natural object in the night sky after the Moon, Venus can cast shadows and can be, on rare occasion, visible to the naked eye in broad daylight.Venus lies within Earth\'s orbit, and so never appears to venture far from the Sun, either setting in the west just after dusk or rising in the east a bit before dawn.',['https://media.wired.com/photos/5e59ad2b79c7100008eb6ae8/125:94/w_2000,h_1504,c_limit/photo_space_venus_1_S91-50688.jpg','https://media.wired.com/photos/5dae3d8e182de80009f7fdb6/1:1/w_1599,h_1599,c_limit/science_nasa_Venus!.jpg','https://cdn.mos.cms.futurecdn.net/kaPwBjHiUKax8syodHNPmF-320-80.jpg']),
  Planets('3','Earth','assets/images/earth.png','Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating estimation and other evidence, Earth formed over 4.5 billion years ago. Earth\'s gravity interacts with other objects in space, especially the Sun and the Moon, which is Earth\'s only natural satellite.',['https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/1200px-The_Earth_seen_from_Apollo_17.jpg','https://media4.s-nbcnews.com/i/newscms/2019_14/2812016/190405-earths-core-al-1504_5c22d34d868c60024dba8bbdc8e981ad.jpg','https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fstartswithabang%2Ffiles%2F2018%2F12%2Fkepler186f_artistconcept_2.jpg']),
  Planets('4','Mars','assets/images/mars.png','Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being only larger than Mercury. In English, Mars carries the name of the Roman god of war and is often referred to as the "Red Planet".The latter refers to the effect of the iron oxide prevalent on Mars\'s surface, which gives it a reddish appearance distinctive among the astronomical bodies visible to the naked eye.',['','']),
  Planets('5','Jupiter','assets/images/jupiter.png','Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter is one of the brightest objects visible to the naked eye in the night sky, and has been known to ancient civilizations since before recorded history. It is named after the Roman god Jupiter.',['','']),
  Planets('6','Saturn','assets/images/saturn.png','Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine times that of Earth.It only has one-eighth the average density of Earth; however, with its larger volume, Saturn is over 95 times more massive.',['','']),
  Planets('7','Uranus','assets/images/uranus.png','Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus, who, according to Greek mythology, was the grandfather of Zeus (Jupiter) and father of Cronus (Saturn). It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.',['','']),
  Planets('8','Neptune','assets/images/neptune.png','Neptune is the eighth and farthest-known planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, slightly more massive than its near-twin Uranus. Neptune is denser and physically smaller than Uranus because its greater mass causes more gravitational compression of its atmosphere.',['','']),
];
